#- connection:
#    port: 12344
#maxClients: 20
#loginTimeout: 30000
# If set, all messages are immediately flushed to the clients.
#instantFlush: false
#maze:
# allowed values: random, template, map
#generatorMode: random
#generatorParameters:
#width: 40
#height: 30
#mapFile: null
#map-file: donut.mzt
#map-file: contest.mzt
#map-file: square.mzt
# TODO: distinguish between resources and files
#  serverBots:
#    autoLaunch: #[]
#      - dummy
#      - dummy
#      - dummy
#    specialBots:
#dummy: dummy
#      trapeater: trapeater
#frenzy: frenzy
#      frenzy: FrenzyFrede
#spectator: spectator
#      spectator: commander
#game:
# allowed values: unlimited, ultra, fast, normal, slow, ultra-slow
# unlimited is 1ms and should only be used if you know, what you are doing
# in "unlimited" mode, delay-compensation is always off
#initialSpeed: normal
#generateBaitsAtStart: true
#autoTrapeater: true
#allowSpectator: true
#delayCompensation: true
#baitGenerator:
#objectDivisor: 26
#trapDivisor: 4
- connection:
    port: 12345
  maze:
    generatorMode: template
    generatorParameters:
      mapFile: square.mzt
  serverBots:
    autoLaunch:
      - dummy
      - dummy
      - dummy
      - ninja_ng
      - mindripper
      - underdog
      - chopstick
      - bloodhound
      - FrenzyFrede
    specialBots:
      trapeater: trapeater
      frenzy: FrenzyFrede
      spectator: commander
    nickMappings:
      dummyNames:
        - aimless
        - yanni
        - le_dieter
        - simon
        - no_den
        - eclair
        - joe
      trapeaterNames:
        - m√ºllschlucker
        - wall-e
        - pacman
      frenzyNames: [ ]
      freeNickMappings:
        - botName: chopstick
          additionalNames:
            - philosopher
  game:
    initialSpeed: fast
    events:
      enabled: true
- connection:
    port: 12344