- connection:
    port: 12345
  maze:
    generatorMode: random
    generatorParameters:
      width: 40
      height: 30
  serverBots:
    autoLaunch: [ ]
    specialBots:
      trapeater: trapeater
      spectator: spectator
  game:
    initialSpeed: normal
    generateBaitsAtStart: true
    allowSpectator: true
    delayCompensation: true
    events:
      enabled: true
      allGemProbability: 0.0
